### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by GoranMilovanovic** [mlampros/textTinyR#1]
A call to `devtools::install_github('mlampros/textTinyR')`

produces:

`export_all_funcs.cpp:17:30: fatal error: boost/locale.hpp: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:141: recipe for target 'export_all_funcs.o' failed
make: *** [export_all_funcs.o] Error 1
ERROR: compilation failed for package ‘textTinyR’`

aftering sucessfully updating {data.table} and {RcppArmadillo}

**Comment by mlampros** [comment]
currently there is an issue with the boost locale header file, that the textTinyR package uses. In which operating system do you work?

**Comment by GoranMilovanovic** [comment]
Ubuntu 16.04 (Xubuntu, to be precise, if that makes any difference).

**Comment by mlampros** [comment]
This is a temporary solution. Open a console and run the following commands:

sudo apt-get install libboost-all-dev
sudo apt-get update
sudo apt-get install libboost-locale-dev


They will install the boost library (including the locale).

After running those commands, open a new R session and install the textTinyR using the devtools::install_github('mlampros/textTinyR').

Please tell me if it works

**Comment by GoranMilovanovic** [comment]
Thanks! - Up and running:

`** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (textTinyR)`

Important: if you need ANY help with this package - and since I am not in C++, that means: any R development, developing new features, testing, etc. - please let me know. 

Best Regards,
Goran

**Comment by mlampros** [comment]
good to hear that. If you think that something can be added or updated I'm open to suggestions. I have to say I'm not a C++ programmer too, I've started learning this language 6-8 months ago.
You can close this issue if the package works as expected.

**Comment by GoranMilovanovic** [comment]
Well, you seem to be doing great if that's a 6-8 months experience only. I haven't touched C since mid-90s or so. Anyways, I will be testing your package, providing feedback if I see anything that needs improvement, and I hope you don't mind if I share an idea or two with you on possible new package functionality.

Closing the issue. Thanks again!
