### ISSUE TITLE
Error reading word-vectors in model initialization

### ISSUE THREAD

**Issue by tredmill** [mlampros/textTinyR#10]
I am encountering an error while trying to initialize a doc2vec model: 

"pre-processing of input data starts ...
File is successfully opened
total.number.lines.processed.input: 55000
creation of index starts ...
intersection of tokens and wordvec character strings starts ...
modification of indices starts ...
final processing of data starts ...
File is successfully opened
total.number.lines.processed.output: 55000

**Error: after pre-processing the word-vectors it appears that the terms-vector is an empty object**". 

It seems a simple mistake, but i cannot figure it out. The model code is:

textTinyR::Doc2Vec$new(token_list = tokens, 
                              word_vector_FILE = "word_vectors.txt",
                              print_every_rows = 5000, 
                              verbose = TRUE,                    
                              copy_data = FALSE) 

Tokens is a list of tokens per document, tokenized using word_tokenizer() from text2vec:

tokens <- word_tokenizer(text)
tokens[[i]]
 [1] "rente"          "krise"          "das"            "obi"           
 [5] "bge"            "bietet"         "antworten"      "auf"           
 [9] "den"            "technischen"    "wandel"         "und"           
[13] "das"            "ende"           "year"           "close"         
[17] "to"             "basic"          "income"         "for"           
[21] "all"            "bien"           "bge"            "obi"           
[25] "das"            "grundeinkommen" "ein"            "jahr"          
[29] "naher"          "gekommen"       "bge" 

"word_vectors.txt" is the path to a .txt file with word embeddings, with i rows of words and j columns of hidden nodes. The embeddings are estimated using the GloVe algorithm in text2vec. The code and sample output:

glove = GlobalVectors$new(word_vectors_size = 50, vocabulary = vocab, x_max = 10)
wv_main = glove$fit_transform(tcm, n_iter = 10, convergence_tol = 0.01)
wv_context = glove$components
word_vectors = wv_main + t(wv_context)

word_vectors[1:2,]
"ufo" 0.268469959497 0.0655194278806 0.281089767813 -0.558465510606766
"finland" -0.047915056347 0.156950026750 -0.2235322073-0.0563018918037

What is the correct way to provide the word vectors to the Doc2Vec function?

**Comment by mlampros** [comment]
hi @tredmill and I'm sorry for the late reply,

it would be nice if you've added also sample text to your example case. However, I reproduced your error with the following code snippet,

```R

# http://text2vec.org/glove.html

library(text2vec)
text8_file = "~/text8"
if (!file.exists(text8_file)) {
  download.file("http://mattmahoney.net/dc/text8.zip", "~/text8.zip")
  unzip ("~/text8.zip", files = "text8", exdir = "~/")
}
wiki = readLines(text8_file, n = 1, warn = FALSE)
length(wiki)

# Create iterator over tokens
tokens = space_tokenizer(wiki)
# Create vocabulary. Terms will be unigrams (simple words).
it = itoken(tokens, progressbar = FALSE)
vocab = create_vocabulary(it)

vocab = prune_vocabulary(vocab, term_count_min = 5L)

# Use our filtered vocabulary
vectorizer = vocab_vectorizer(vocab)
# use window of 5 for context words
tcm = create_tcm(it, vectorizer, skip_grams_window = 5L)

glove = GlobalVectors$new(word_vectors_size = 50, vocabulary = vocab, x_max = 10)
wv_main = glove$fit_transform(tcm, n_iter = 10, convergence_tol = 0.01)

dim(wv_main)

wv_context = glove$components
dim(wv_context)

word_vectors = wv_main + t(wv_context)

word_vectors[1:2,]

terms = rownames(word_vectors)
terms[1:2]

pth_file = "word_vectors.txt"

fileConn<-file(pth_file)
writeLines(sapply(1:nrow(word_vectors), function(x) paste(c(terms[x], word_vectors[x, ]), collapse = " ")), fileConn)
close(fileConn)

# create random character strings which highly probable do not match any of the input words
set.seed(1)
text_vec = sapply(1:15, function(y) paste(sapply(1:10, function(x) paste(sample(letters, sample(4:10, 1)), collapse = "")), collapse = " "))
length(text_vec)

tokens <- text2vec::word_tokenizer(text_vec)

tokens[[1]]

```

The error you receive is due to the fact that there is no matched word between your input text and the reduced word vectors. In your code you use 

```R

copy_data = FALSE

```
This throws an error from the Rcpp side of the *Doc2Vec* function because the output object is of length 0.

If you set the *copy_data* parameter to TRUE then, 

```R

init = textTinyR::Doc2Vec$new(token_list = tokens,
                                word_vector_FILE = "word_vectors.txt",
                                print_every_rows = 5,
                                verbose = TRUE,
                                copy_data = TRUE)

res_wv = init$pre_processed_wv() 
str(res_wv)

List of 2
 $ terms_reduced_wordvecs  : chr(0) 
 $ reduced_wordvecs_pointer: list()

```

you will observe that the output *terms* and *reduced_wordvecs_pointer* are empty ( that's why you receive the error when *copy_data=FALSE* ).

You can also read my [blog post](http://mlampros.github.io/2018/04/04/extending_textTinyR_package/) where I make a mention to the *pre_processed_wv()* R6 method.

**Comment by tredmill** [comment]
Thank you for the swift response and elaborate example. Apparently the problem was the use of quotes in the vector names. Thus, the word_vectors.txt document should have words as unquoted row names and embeddings separated by space in the columns.
