### ISSUE TITLE
Using file path of pre saved word vectors with textTinyR (Doc2Vec) doesn't work.

### ISSUE THREAD

**Issue by adjoshi81** [mlampros/textTinyR#6]
@mlampros: This is with reference to the stackoverflow link related to an error while reading the pre-
saved word_vectors file in the Doc2Vec function: https://stackoverflow.com/questions/52147678/using-file-path-of-pre-saved-word-vectors-with-texttinyr-doc2vec?noredirect=1#comment91268496_52147678

The input data is attached here:
[Sample_Text.xlsx](https://github.com/mlampros/textTinyR/files/2348341/Sample_Text.xlsx)

The R code is also attached. 
[RCode.txt](https://github.com/mlampros/textTinyR/files/2348388/RCode.txt)

It basically does following processes in that order: 1. regex cleaning, 2. word elongation substitution, 3. collocation (2 and 3 word phrases identification through quanteda), 4. tokenize the text and substitute individual tokens with phrases found in (3), 5. create a feature*feature matrix, 6. run a glove model (from text2vec), 7. create word_vectors object (which is the output), 8. write the word_vectors.txt in the working directory, 9. Has doc2vec invoked twice.

The error at step (9) is: Error in reduced_word_vectors(self$word_vector_FILE, private$unq_tok,  : 
  Expecting a string vector: [type=list; required=STRSXP]. 

Placing this file in the textTinyR (where a similar file called word_vec.txt exists) also didn't help resolve the error.

I would appreciate if you can suggest me a way to overcome this error.

Thanks.

**Comment by mlampros** [comment]
@adjoshi81 I modified the following lines of the *RCode.txt* file in order to input / process the data,

```R
require(xlsx)

ip_1 <- read.xlsx2("Sample_Text.xlsx", sheetIndex = 1, stringsAsFactors = FALSE, header = TRUE)

```

Actually the problem was that the *tokens3* object is of class "tokens" and can not be converted directly to a list of character vectors - which the *Doc2Vec* requires - using *list(tokens3)*. The following works for me based on the pre-processing of the *RCode.txt* fille you've attached,

```R

tmp_list = lapply(tokens3, function(x) x)      # conversion to a list of character vectors
str(tmp_list)

doc_vectors <- Doc2Vec$new(token_list = tmp_list, word_vector_FILE = "word_vectors.txt", 
                             print_every_rows = 10000, verbose = TRUE, copy_data = FALSE)

doc2_sum = doc_vectors$doc2vec_methods(method = "sum_sqrt", threads = 1)
str(doc2_sum)

doc2_norm = doc_vectors$doc2vec_methods(method = "min_max_norm", threads = 2)
str(doc2_norm)

```

To use the last method of the *Doc2Vec* R6 class (*method = "idf"*) you need the *global_term_weights* , which you can obtain based on the [notes of the blog post](http://mlampros.github.io/2018/04/04/extending_textTinyR_package/).

Please let me know if it worked for you too.

**Comment by mlampros** [comment]
@adjoshi81, it is good that it worked for you too.

The 3 methods that I've used are based mainly on two blog posts [Is That a Duplicate Quora Question?](https://www.linkedin.com/pulse/duplicate-quora-question-abhishek-thakur) and [Duplicate Question Detection with Deep Learning on Quora Dataset](http://www.erogol.com/duplicate-question-detection-deep-learning/). I've included those two also at the end of the [blog post (References)](http://mlampros.github.io/2018/04/04/extending_textTinyR_package/) where I explained the new functionality of the textTinyR package.
