### ISSUE TITLE
Is the doc2vec function in textTinyR the same as the Paragraph Vector model?

### ISSUE THREAD

**Issue by hanson1005** [mlampros/textTinyR#9]
Hi again.
I am following your template at
https://cran.r-project.org/web/packages/textTinyR/vignettes/word_vectors_doc2vec.html

It seems that you first fit a fasttext model to create word2vec and then as the second step you fit a doc2vec model using the doc2vec command in textTinyR package.

Is the doc2vec model generated through this two step process the same as the Paragraph Vector model (either PV-DM or PV-DBOW) as described in Le & Mikolov (2014) paper?

When I read this paper and the tutorial using gensim in Python, the doc2vec is a one single model rather than an output fit through a two step process as described in your template. How is the output from your process different from the Paragraph Vector model's output?

Also, if they are the same things, if I fit a skip-gram model in the first stage using fasttext, in the second stage using doc2vec, am I fitting a PV-DBOW model? And if I fit a cbow model in the first stage, then am I fitting a PV-DM in the second stage?

Also, how does the three methods of doc2vec (e.g. sum_sqrt, min_max_norm
or idf) relate to the PV model?

Hope to hear from you soon. Thank you!

**Comment by mlampros** [comment]
hi @hanson1005,

first of all I'm sorry for the delay regarding the 'fasttext' R package. I'm still waiting the response from CRAN.

To your question : The approach that I follow in my vignette 'word_vectors_doc2vec' is based on the following two blogs ( and not on the paper that you've mentioned ):

- [https://www.linkedin.com/pulse/duplicate-quora-question-abhishek-thakur](https://www.linkedin.com/pulse/duplicate-quora-question-abhishek-thakur)
- [http://www.erogol.com/duplicate-question-detection-deep-learning/](http://www.erogol.com/duplicate-question-detection-deep-learning/)

My intention was to perform clustering based on one of the three (sum_sqrt, min_max_norm or idf) 'doc2vec_methods'.

I've used gensim in the past, but if I remember correctly only the LDA function, so I'm not sure if my two step approach is similar to Gensim's doc2vec function. 

hopefully I answered your questions.
